### ISSUE TITLE
Lines between comments are removed

### ISSUE THREAD

**Issue by PaulHenri8080** [Roberto-XY/eunomo#22]
Hi,

It might be linked to this issue: #21 but it is not quite the same symptoms.

When using the formater i have the following diff :
<img width="1588" alt="image" src="https://github.com/Roberto-XY/eunomo/assets/97036267/8d2ccc1b-7dad-4137-8b56-72831ac58412">

A line trapped between two comments is sometimes removed, not always though. Another example where it is handled correctly : 
<img width="1574" alt="image" src="https://github.com/Roberto-XY/eunomo/assets/97036267/936eb7d9-c5fd-47c3-9af9-06d6bd210f15">

I can make more tests if needed.

P.S : Fantastic plugin otherwise, great idea and will save us a lot of time 💪

**Comment by ashleyhindle** [comment]
Where could I start looking into this if needed @Roberto-XY ? This issue worries me slightly, but I really want to use eunomo 😁

**Comment by Roberto-XY** [comment]
Hey! Thanks for wanting to tackle this, I had not much time to invest in this project lately.

To format the code, the application looks at the AST. The tricky part is that comments are not part of the AST. I already started with some work some months ago & pushed it [here](https://github.com/Roberto-XY/eunomo/pull/23) now. It may or may not help since it is _heavily_ WIP and I did not look at that code for a _long_ time.

I'll try to find some time to give more support :+1:

**Comment by Roberto-XY** [comment]
@ashleyhindle @PaulHenri8080  I _finally_ found some time to approach this issue. If you like, you can test the new version under [v3.0.0-preview](https://github.com/Roberto-XY/eunomo/releases/tag/v3.0.0-preview). It is not released to hex yet, as I would welcome some feedback before. Closing this issue once a working version is released.

**Comment by ashleyhindle** [comment]
> @ashleyhindle @PaulHenri8080 I _finally_ found some time to approach this issue. If you like, you can test the new version under [v3.0.0-preview](https://github.com/Roberto-XY/eunomo/releases/tag/v3.0.0-preview). It is not released to hex yet, as I would welcome some feedback before. Closing this issue once a working version is released.

@Roberto-XY this works super well, thanks for sorting 🙌  I've not been able to break it/cause another bug so far

![2024-05-15 10 15 57](https://github.com/Roberto-XY/eunomo/assets/454975/205ee316-ffce-4f8c-a3e8-eb48bed48733)

**Comment by Roberto-XY** [comment]
Published to https://hex.pm/packages/eunomo


Closing
